# Generated by `specgate ci init --provider azure`
# Spec-Driven Development gate for Azure Pipelines.
trigger:
  branches:
    include: [main]
pr:
  branches:
    include: ['*']

pool:
  vmImage: ubuntu-latest

steps:
{{SETUP_STEPS}}

  - script: |
      {{GATE_CMD}}
    displayName: The gate — the specification and the tests

  # Supply-chain gate: fails when rendered pack content no longer matches the
  # digest pinned in .specops.lock. Skipped when no packs are installed.
  - script: |
      if [ -f .specops.lock ]; then
        npx @rsaglobaltech/specgate@{{SPECGATE_VERSION}} validate . --against-lock
      else
        echo "No .specops.lock — no packs installed, nothing to check."
      fi
    displayName: Check pack drift

  - script: npx @rsaglobaltech/specgate@{{SPECGATE_VERSION}} plan --project-dir . --format json > $(Build.ArtifactStagingDirectory)/spec-plan.json
    condition: always()
    displayName: Export pending-work plan

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)/spec-plan.json
      artifactName: spec-plan
