# Generated by `specgate ci init --provider github`
# Spec-Driven Development gate: no PR merges if a requirement loses its
# feature file, its test artifact or its traceability row — or if the
# project's tests fail.
name: Spec gate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  spec-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
{{SETUP_STEPS}}
      - name: The gate — the specification and the tests
        run: |
          {{GATE_CMD}}
      # Supply-chain gate: fails when the rendered pack content no longer
      # matches the digest pinned in .specops.lock — a moved tag, a rewritten
      # history, or a hand-edited generated file. Skipped when the project
      # installs no packs.
      #
      # Packs in a private repository: add a SPECOPS_TOKEN secret with read
      # access to it, and git uses it for github.com. Without one, nothing changes.
      - name: Check pack drift
        env:
          SPECOPS_TOKEN: ${{ secrets.SPECOPS_TOKEN }}
        run: |
          if [ -n "$SPECOPS_TOKEN" ]; then
            git config --global url."https://x-access-token:${SPECOPS_TOKEN}@github.com/".insteadOf "https://github.com/"
          fi
          if [ -f .specops.lock ]; then
            npx @rsaglobaltech/specgate@{{SPECGATE_VERSION}} validate . --against-lock
          else
            echo "No .specops.lock — no packs installed, nothing to check."
          fi
      - name: Export pending-work plan
        if: always()
        run: npx @rsaglobaltech/specgate@{{SPECGATE_VERSION}} plan --project-dir . --format json > spec-plan.json
      - name: Upload plan artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spec-plan
          path: spec-plan.json
