/** What a team wires around the loop: CI, agent files, upgrades. */
import * as fs from "node:fs";
import * as path from "node:path";

export default [
  {
    name: "ci init writes a workflow that runs the one gate",
    covers: ["ci init"],
    run(dir, t) {
      t.nodeRepo(dir);
      t.ok(t.sg(dir, "init"), "init");
      t.ok(t.sg(dir, "ci", "init", "--provider", "github"), "ci init --provider github");
      const wf = fs
        .readdirSync(path.join(dir, ".github", "workflows"))
        .map((f) => t.read(dir, `.github/workflows/${f}`))
        .join("\n");
      t.expect(/validate \. --strict\b/.test(wf), "the workflow runs validate --strict");
      t.expect(!/--strict-tdd/.test(wf), "and not the weaker --strict-tdd");
    },
  },
  {
    name: "agents init writes /specgate:* commands for the daily loop",
    covers: ["agents init"],
    run(dir, t) {
      t.nodeRepo(dir);
      t.ok(t.sg(dir, "init"), "init");
      t.ok(t.sg(dir, "agents", "init", "--tool", "claude,cursor"), "agents init");
      t.expect(t.exists(dir, ".cursor/rules/specgate.mdc"), "cursor rule named specgate");
      t.expect(/# \/specgate:apply/.test(t.read(dir, ".claude/commands/specgate/apply.md")), "heading");
      for (const step of ["explore", "new", "apply", "verify", "done"]) {
        t.expect(t.exists(dir, `.claude/commands/specgate/${step}.md`), `the daily loop has /specgate:${step}`);
      }
      t.expect(/specgate check --json/.test(t.read(dir, ".claude/commands/specgate/verify.md")), "verify runs check");
      t.expect(/names `REQ-NNN`/.test(t.read(dir, "AGENTS.md")), "AGENTS.md teaches the mention as the link");
    },
  },
  {
    name: "update moves agent files generated by 0.9.0, keeping a team's edit",
    covers: ["update"],
    network: true,
    run(dir, t) {
      t.needsNetwork();
      t.nodeRepo(dir);
      t.ok(t.sg(dir, "init"), "init");
      const old = t.run("npx", ["-y", "@rsaglobaltech/specgate@0.9.0", "agents", "init", "--tool", "claude,cursor"], {
        cwd: dir,
      });
      t.expect(old.status === 0, "0.9.0 agents init (needs the network)", old);
      t.expect(t.exists(dir, ".claude/commands/csda/apply.md"), "0.9.0 wrote csda paths");
      fs.appendFileSync(path.join(dir, ".claude/commands/csda/apply.md"), "\nOUR TEAM RULE\n");
      t.write(dir, "README.md", "# Our project\n");

      t.ok(t.sg(dir, "update"), "update");
      t.expect(!t.exists(dir, ".claude/commands/csda"), "old directory removed");
      const moved = t.read(dir, ".claude/commands/specgate/apply.md");
      t.expect(moved.includes("OUR TEAM RULE"), "the team's edit survived");
      t.expect(!/\/csda:/.test(moved), "no /csda: left");
      t.expect(t.read(dir, "README.md") === "# Our project\n", "the project README is untouched");
      const again = t.json(t.sg(dir, "update", "--json"));
      t.expect(again.update.files.every((f) => f.outcome === "unchanged"), "a second update is a no-op");
    },
  },
];
