/**
 * What `init --multi-stack` decides, with no filesystem underneath it.
 *
 * The shape this produces exists because of one constraint that is easy to get
 * wrong: three stacks implementing the same product share their *requirements*
 * and their *scenarios*, and share nothing else. A requirement is the same
 * sentence whether Spring or Quarkus implements it, and a Gherkin scenario
 * describes behaviour, which is the point of writing it in Gherkin. But the
 * traceability matrix maps a requirement to the file that implements it and the
 * file that proves it, and those are different files in every stack — so the
 * matrix cannot be shared, and neither can AGENTS.md, which is the rulebook
 * for one toolchain.
 *
 * Sharing the first set and splitting the second is the whole design. Copying
 * everything would be simpler and would be a lie: editing the spec in one
 * project would leave the other two describing a different product.
 */

/** Paths that are one artifact for the whole tree, held at the root. */
export const SHARED_PATHS = ["spec.md", "features", "docs/specs/adr"] as const;

/** Paths each stack owns outright — they name files that differ per toolchain. */
export const PER_STACK_PATHS = ["AGENTS.md", "README.md", "docs/specs/traceability.md"] as const;

export interface StackPlan {
  /** Directory name under the root, and the value of STACK for that project. */
  name: string;
  /** How `projects:` in specops.config.yaml refers to it. */
  entry: string;
}

export interface MultiStackPlan {
  stacks: StackPlan[];
}

export class InvalidStackList extends Error {}

/**
 * Turn `--multi-stack spring,quarkus,micronaut` into the plan.
 *
 * Each name becomes a directory, so it has to survive being one. A stack called
 * `../etc` would write outside the root the user named, and `projects:` already
 * accepts relative paths that nobody checks stay inside the repository (#103) —
 * no reason to open a second door to the same place.
 */
export function planStacks(raw: string): MultiStackPlan {
  if (typeof raw !== "string" || raw.trim() === "") {
    throw new InvalidStackList("--multi-stack needs a comma-separated list, e.g. spring,quarkus");
  }

  const names = raw
    .split(",")
    .map((s) => s.trim())
    .filter((s) => s !== "");

  if (names.length < 2) {
    throw new InvalidStackList(
      `--multi-stack needs at least two stacks (got ${names.length === 1 ? `'${names[0]}'` : "none"}) — ` +
        "for one stack, plain `specgate init` is the command"
    );
  }

  const seen = new Set<string>();
  for (const name of names) {
    if (!/^[a-z0-9][a-z0-9._-]*$/i.test(name)) {
      throw new InvalidStackList(
        `'${name}' is not usable as a directory name — use letters, digits, dot, dash or underscore`
      );
    }
    if (name === "." || name === ".." || name.includes("..")) {
      throw new InvalidStackList(`'${name}' would write outside the project root`);
    }
    const key = name.toLowerCase();
    if (seen.has(key)) {
      throw new InvalidStackList(`'${name}' is listed twice — each stack is one directory`);
    }
    seen.add(key);
  }

  return { stacks: names.map((name) => ({ name, entry: `./${name}` })) };
}

/**
 * The `projects:` list `validate`, `plan`, `status` and `report` already fan out
 * over. Written by hand rather than through a YAML library because the rest of
 * this project reads it with `parseYamlLite`, and a writer that can emit
 * something its own reader rejects is worse than no writer.
 */
export function renderSpecopsConfig(plan: MultiStackPlan, projectName: string): string {
  return (
    `# Generated by \`specgate init --multi-stack\`.\n` +
    `#\n` +
    `# Every entry is validated as a project in its own right. The spec and the\n` +
    `# scenarios live once, at this root; each stack below carries its own\n` +
    `# traceability matrix, because the files that implement and prove a\n` +
    `# requirement are different files in every stack.\n` +
    `name: ${projectName}\n` +
    `projects:\n` +
    plan.stacks.map((s) => `  - ${s.entry}\n`).join("")
  );
}

/**
 * Where a shared path sits, seen from inside a stack directory.
 *
 * `docs/specs/adr` is two levels down, so the link back is not the same depth
 * as the one for `spec.md`. Getting this wrong produces a link that resolves to
 * nothing and a validate run that reports a missing required file, which is a
 * confusing way to learn about an off-by-one.
 */
export function relativeToRoot(sharedPath: string): string {
  const depth = sharedPath.split("/").length;
  return "../".repeat(depth) + sharedPath;
}
