# Generated by `specgate harness init`
#
# Per-project defaults for `specgate harness run`. Every key is optional, and any
# CLI flag overrides what is written here.
harness_version: 1

# The agent invocation. `{prompt_file}` is replaced with the path to the
# generated per-requirement prompt.
#
# Left commented out on purpose: which agent runs this is your choice and your
# credentials, and a default committed here is a default somebody pays for by
# accident. Pass it explicitly the first few times:
#
#   specgate harness run --req REQ-001 --agent "claude -p < {prompt_file}"
#
# Then uncomment the line you settled on.
#
# agent: "claude -p < {prompt_file}"
# agent: "cursor-agent -p < {prompt_file}"
# agent: "aider --yes --message-file {prompt_file}"

# Or name a profile from .harness/profiles.yaml, so the team commits the
# commands it uses and each environment picks one:
#
#   agent_profile: local-claude
#
#   # .harness/profiles.yaml
#   profiles_version: 1
#   profiles:
#     local-claude:
#       agent: "claude -p < {prompt_file}"
#     ci:
#       agent: "aider --yes --message-file {prompt_file}"
#
# An explicit `agent:` wins over a profile.

# An *additional* gate, on top of the `validate --strict` the harness always
# runs. Left commented out when no build file gave it away — an unset key is
# safe, whereas a placeholder that exits 0 would be a gate that always passes.
#
# Three placeholders are substituted per requirement, so the gate can run the
# scenario belonging to the requirement under test:
#
#   {req}           REQ-007
#   {scenario}      SCN-007
#   {feature_file}  features/billing/refund.feature
#
# Worth using. `validate` checks that the requirement's declared files exist;
# only a test command checks that they do what the scenario says — without one
# of these, a requirement can be marked Implemented with its scenario never run:
#
#   test_cmd: "npm run verify && npm run test:e2e -- {feature_file}"
#
# The harness runs each requirement in a fresh git worktree, which contains only
# what git tracks — so there is no node_modules. Install first if your gate
# needs one, or the agent will spend its attempt doing it:
#
#   test_cmd: "npm ci && npm run verify && npm run test:e2e -- {feature_file}"
{{TEST_CMD_LINE}}

# Retries per requirement, each one fed the previous failure. Past three, the
# loop is usually stuck on something a human needs to read.
max_attempts: 3

# Universal directives — Role, Active Project Boundary, Execution Policy —
# prepended to every per-requirement prompt. Use `prompt_prefix` for a
# one-liner; the file form exists because the realistic version is multi-line.
prompt_prefix_file: ./.harness/prompt-prefix.md

# CI mode: push each green branch and open a PR, leaving review to a human.
# The harness never merges.
# push: true
# remote: origin
# pr_cmd: "gh pr create --head {branch} --title '{req} via harness' --fill"
