/**
 * AGENTS.md as a shared file (ADR-0031).
 *
 * The market's agents read one `AGENTS.md`, and a team often has one before
 * Specgate arrives. Specgate's contract therefore lives in a marked block:
 * created when the file is new, inserted above the team's text when it is
 * not, and replaced in place — and only that block — on every later run.
 * The team's text outside the markers is never rewritten.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { findCliRoot } from "../lib/project-root";

export const BEGIN = "<!-- specgate:begin — generated by specgate; edit outside this block -->";
export const END = "<!-- specgate:end -->";

/** `existing` with the block set to `contract`. */
export function mergeContract(existing: string | null, contract: string): string {
  const block = `${BEGIN}\n${contract.trimEnd()}\n${END}\n`;
  if (existing === null || existing.trim() === "") return block;
  const start = existing.indexOf(BEGIN.slice(0, 22));
  const end = existing.indexOf(END);
  if (start !== -1 && end !== -1 && end > start) {
    return existing.slice(0, start) + block + existing.slice(end + END.length).replace(/^\n/, "");
  }
  return `${block}\n${existing}`;
}

/** The team's text: everything outside the block. */
export function outsideBlock(existing: string): string {
  const start = existing.indexOf(BEGIN.slice(0, 22));
  const end = existing.indexOf(END);
  if (start === -1 || end === -1 || end < start) return existing;
  return (existing.slice(0, start) + existing.slice(end + END.length)).trim();
}

// ── The contract, for a project `init` did not write it for ─────────────────

/** `- Stack: x` (AI_RULES.md) or `… · Stack: x · …` (AGENTS.md). */
export function rulesField(text: string, name: string): string | null {
  const m = new RegExp(`(?:^|·)\\s*-?\\s*\\**${name}:?\\**:?\\s*([^·\\n]+)`, "im").exec(text);
  return m ? m[1].trim() : null;
}

/** `# AI Rules — golden-app` / `# AI Rules - Backend (Shop)` / `# Agent Manifest — Shop`. */
function titleName(text: string): string | null {
  const m = /^#\s+(?:AI[ _]Rules|Agent Manifest)\s*[—–-]\s*(?:\w+\s*\(([^)]+)\)|(.+))$/im.exec(
    text
  );
  return m ? (m[1] || m[2]).trim() : null;
}

/**
 * Text an older Specgate generated into AGENTS.md — `agents init`'s
 * instructions, `init`'s "Agent Manifest". It is replaced whole by the block;
 * a team's own AGENTS.md has neither sentence, and is kept.
 */
const OLDER_SPECGATE = [
  "This project uses Spec-Driven Development through the `specgate` CLI.",
  "This file helps AI coding agents (Claude, Copilot, Cursor, Aider, etc.)",
];

export function writtenByOlderSpecgate(text: string): boolean {
  return OLDER_SPECGATE.some((sig) => text.includes(sig));
}

/**
 * The generated contract with the project's facts read from its existing
 * rules file. The stack's rules stay where the team wrote them — `update`
 * moves them below the block, verbatim — so the block's own rules section
 * points there.
 */
export function buildContract(facts: string, projectDir: string): string {
  const root = findCliRoot(__dirname);
  const tpl = fs.readFileSync(path.join(root, "templates", "base", "AGENTS.md.tpl"), "utf8");
  const vars: Record<string, string> = {
    PROJECT_NAME: (
      rulesField(facts, "Project") ||
      titleName(facts) ||
      path.basename(path.resolve(projectDir))
    ).replace(/\s*\(.*\)$/, ""),
    PROJECT_TYPE: "existing",
    ARCHITECTURE: rulesField(facts, "Architecture") || "minimal",
    DOMAIN: rulesField(facts, "Domain") || "see spec.md",
    STACK: rulesField(facts, "Stack") || "see below",
    API_STYLE: rulesField(facts, "API style") || rulesField(facts, "API integration") || "as built",
    TESTING: rulesField(facts, "Testing") || "see below",
    STACK_RULES: "- The team's own rules follow this block.",
    ARCHITECTURE_MODELING_RULES: "",
    ARCHITECTURE_CHECKS: "",
  };
  return (
    tpl.replace(/\{\{([A-Z_]+)\}\}/g, (all, k) => (k in vars ? vars[k] : all)).trimEnd() + "\n"
  );
}

/**
 * `AGENTS.md` for a project: the block written when missing, inserted above
 * the team's text when the file has none, left alone when it has one.
 * Returns what happened, or null when nothing needed writing.
 */
export function ensureContract(
  projectDir: string,
  opts: { dryRun?: boolean } = {}
): "written" | "block-added" | "replaced" | null {
  const file = path.join(projectDir, "AGENTS.md");
  const found = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (found !== null && found.includes(BEGIN.slice(0, 22))) return null;
  // What an older Specgate generated is replaced, not kept below the block.
  const older = found !== null && writtenByOlderSpecgate(found);
  const existing = older ? null : found;
  const legacy = path.join(projectDir, "AI_RULES.md");
  const facts = [fs.existsSync(legacy) ? fs.readFileSync(legacy, "utf8") : "", found || ""].join(
    "\n"
  );
  if (!opts.dryRun) {
    fs.writeFileSync(file, mergeContract(existing, buildContract(facts, projectDir)), "utf8");
  }
  return older ? "replaced" : found === null ? "written" : "block-added";
}

/**
 * ADR-0031's migration: AI_RULES.md's text moves, verbatim, below the block in
 * AGENTS.md, and AI_RULES.md goes. Git keeps the old file; nothing is lost.
 */
export function migrateAiRules(
  projectDir: string,
  opts: { dryRun?: boolean } = {}
): { moved: boolean; agents: "written" | "block-added" | "replaced" | null } {
  const legacy = path.join(projectDir, "AI_RULES.md");
  if (!fs.existsSync(legacy)) return { moved: false, agents: null };
  const rules = fs.readFileSync(legacy, "utf8").trim();
  const agents = ensureContract(projectDir, opts);
  if (!opts.dryRun) {
    const file = path.join(projectDir, "AGENTS.md");
    const current = fs.readFileSync(file, "utf8").trimEnd();
    const moved = rules.replace(/^#\s+.*\n+/, "");
    fs.writeFileSync(
      file,
      `${current}\n\n## Project rules (from AI_RULES.md)\n\n${moved}\n`,
      "utf8"
    );
    fs.rmSync(legacy);
  }
  return { moved: true, agents };
}
